### ISSUE TITLE
advertise content in the  project pythia collection

### ISSUE THREAD

**Issue by dcherian** [podaac/tutorials#144]
It would be good to add this repo to the list at https://projectpythia.org/resource-gallery.html

**Comment by cassienickles** [comment]
Currently there is a PR to pull in the cookbook into project pythia: https://github.com/ProjectPythia/projectpythia.github.io/pull/385

**Comment by cassienickles** [comment]
Advertised! The team got the above PR through 🎉

**Comment by dcherian** [comment]
Nice work!
