### ISSUE TITLE
Location of orbit incorrect

### ISSUE THREAD

**Issue by bbuzz31** [podaac/tutorials#228]
If you run this notebook: https://github.com/podaac/tutorials/blob/master/notebooks/datasets/Localmachine_SWOT_Oceanography.ipynb

The orbit path doesn't match the image:

From original notebook:
![image](https://github.com/podaac/tutorials/assets/15522503/339ac4c6-3e6f-476c-a57b-c79a8902e065)

From running notebook locally:
![image](https://github.com/podaac/tutorials/assets/15522503/fb7d4fc1-a0ee-4a52-9154-389770223f62)

**Comment by cassienickles** [comment]
Thanks Brett, I've corrected the outputs! The PR #231 is merged and it should be updated in the cookbook shortly!
