### ISSUE TITLE
Regrid L2 SWOT data

### ISSUE THREAD

**Issue by nilsleh** [podaac/tutorials#229]
Thanks for the tutorials, the [Localmachine_SWOT_Oceanogrophy notebook](https://github.com/podaac/tutorials/blob/master/notebooks/datasets/Localmachine_SWOT_Oceanography.ipynb) is very helpful for accessing and downloading SWOT data. 

This is my first time working with SWOT data, and therefore possibly a naive question, however, I have the following data processing problem.

The downloaded data comes with the coordinates:

![Screenshot from 2024-07-02 15-32-31](https://github.com/podaac/tutorials/assets/35272119/59322831-6a5e-4a94-96bd-ce0e43fd3e02)

However, I am wondering how one could regrid the collection of different individual files to a common "composite" such that SWOT data could be paired with other data sources that come in time/lat/lon coordinates like the one available on Copernicus for example:

![image](https://github.com/podaac/tutorials/assets/35272119/9624c2fc-b0a4-43cb-ad64-d12fc5752586)

You mention in the download tutorial that "Level 2 data (non-gridded), specifically, suffers from some of the assumptions made [by xarray]", however, I would imagine that it is still very handy to have a gridded product and therefore I am wondering whether you have suggestions or pointers to how to reasonably process the SWOT data to obtain a gridded product that can be paired with other data sources. 

One tool I found is [xESMF](https://github.com/pangeo-data/xESMF), however, not sure if it's the correct one or what the proper usage with the SWOT data product would be.

Thanks in advance.

**Comment by cassienickles** [comment]
Hi @nilsleh, I am not a SWOT oceanography expert, but I do wonder if a Level 3 product that AVISO produces would meet your need. As of right now, the data access tutorials on our page only deal with the L2 data that PO.DAAC hosts, but AVISO has L3 products too. You can find more information about the L3 product here: https://www.aviso.altimetry.fr/en/data/products/sea-surface-height-products/global/swot-l3-ocean-products.html and they have a page dedicated to how to access from their platforms and the difference between the products here: https://www.aviso.altimetry.fr/en/missions/current-missions/swot/access-to-data.html

In the future, if you have any specific SWOT data product related questions, please feel free to post on this Earthdata Forum Topic: https://forum.earthdata.nasa.gov/viewtopic.php?t=5270&_ga=2.249164295.1437785530.1719854366-1354658737.1715875596 and your question should make its way to the experts.

**Comment by nilsleh** [comment]
Thanks for the reply. The Aviso Level 3 product has the same format, and is also not gridded. Thanks for the Earthdata forum link, I'll try there!
