### ISSUE TITLE
"Search SWOT Passes over Time" Binder not loading

### ISSUE THREAD

**Issue by lily-dove** [podaac/tutorials#245]
Hi there, I'm getting a 500: internal server error when I try to access the "Search SWOT Passes over Time" Binder application from the SWOT Data Tutorial.

**Comment by cassienickles** [comment]
PO.DAAC does not maintain the Binder application for this; we received this information from CNES [here](https://github.com/CNES/search_swot/tree/master). If the issue persists, you can access the extensive Jupyter Notebook directly [here](https://github.com/CNES/search_swot/blob/master/notebook.ipynb).
