### ISSUE TITLE
Update UAT environments to Production Envrionments

### ISSUE THREAD

**Issue by mike-gangl** [podaac/tutorials#45]
A [user mentioned issues](https://github.com/podaac/data-subscriber/issues/69) with netrc and not knowing if we should be using UAT or non-UAT instances in the tutorials and subscriber toolsets. now that a lot of our data is in the cloud, we should update our tutorials and notebooks to the non-UAT instances to remove misunderstandings from our dev users. This will also be a good chance to ensure our tutorials are still working after the transition from dev/test to production.

@ScienceCat18 i'm not saying that you have to own this and do the work, i think you're in the best position to assign, prioritize, and track this work.

**Comment by mike-gangl** [comment]
per haps we can prioritize the repos we update, looking at our metrics (which aren't perfect, but it's all we have)

![Screen Shot 2022-05-09 at 11 52 09 AM](https://user-images.githubusercontent.com/59702631/167477822-480fb3dd-fbd0-4170-b806-c0b82a446a48.png)

* https://github.com/podaac/tutorials/tree/master/notebooks/meetings_workshops/swot_ea_hackweek_2022
* https://github.com/podaac/tutorials/tree/master/notebooks/meetings_workshops/workshop_osm_2022 
* https://github.com/podaac/tutorials/blob/master/notebooks/batch_download_podaac_data.md
* https://github.com/podaac/tutorials/blob/master/notebooks/meetings_workshops/workshop_osm_2022/ECCO_ssh_sst_corr.ipynb
* https://github.com/podaac/tutorials/blob/master/notebooks/opendap/MUR-OPeNDAP.ipynb
* https://github.com/podaac/tutorials/blob/master/notebooks/SWOT-EA-2021/Colocate_satellite_insitu_ocean.ipynb

**Note**: they may not all have UAT links currently (hooray) but these were the top links that we should ensure are being updated if needed.

**Comment by ScienceCat18** [comment]
Thanks @mike-gangl, will look into this and delegate/work it accordingly. This may fold in well with our resources reorganization/curation effort that's just underway, with @cassienickles.

**Comment by sanAkel** [comment]
Hi @mike-gangl, @ScienceCat18, All, if you folks are okay with a few suggestions, specifically [readme](https://github.com/podaac/tutorials/blob/master/README.md)? It would be helpful to tell us (_users_) what things like `Harmony, CMR` mean and differ from `Direct cloud access`, i.e., the `Services and Tools` column of the table.

(Some where I could find a good explanation of the Common Metadata Repository; CMR, but it would have been helpful it was organized from the _top_.) 

Thanks!

**Comment by mike-gangl** [comment]
That's another good suggestion. We have a lot of information across many different places (and within the tutorials themselves, but not a clear topological view/dive into the key services that's easily accessible.

**Comment by edshred2000** [comment]
I’m fixing modis Ard script that has other problem with lib dependencies.

  - ed

On May 9, 2022, at 5:28 PM, Catalina O. ***@***.***> wrote:

﻿

Thanks @mike-gangl<https://urldefense.us/v3/__https://github.com/mike-gangl__;!!PvBDto6Hs4WbVuu7!ZdRvgk_RtnG3kuAfMf3nGG5yXxUc94S-IdpCTpgon_TGvWgA93tDi-qDMYg3KNfoock5yVDUtu6-$>, will look into this and delegate/work it accordingly. This may fold in well with our resources reorganization/curation effort that's just underway, with @cassienickles<https://urldefense.us/v3/__https://github.com/cassienickles__;!!PvBDto6Hs4WbVuu7!ZdRvgk_RtnG3kuAfMf3nGG5yXxUc94S-IdpCTpgon_TGvWgA93tDi-qDMYg3KNfoock5ydSs-sjY$>.

**Comment by ScienceCat18** [comment]
Yes, @mike-gangl and @sanAkel, completely agree, and thank you for the suggestion. It's sometime we're actually working on more recently, to create a better topological roadmap to the resources, and also provide a "glossary" of what the various services are, and where they may be helpful in a user's workflow. @cassienickles and I are working on several things including better organizing the github tutorials repo and the connecting them to the PODAAC web portal, in a way that is easy to navigate and find answers/resources. Stay tuned! but keep the suggestions coming, they are very helpful.

**Comment by sanAkel** [comment]
Thanks for being open to suggestions!

- A list of [requirements as in](https://github.com/podaac/tutorials/blob/master/notebooks/s3/environment.yml) is good to know.
- Many notebooks say that access must be AWS (us-west-2 region). So how does one get that? And if one cannot establish that, what are the alternatives (http, ...) and which examples could be followed?
- What are the known issues? Given the heavy reliance on xarray?

I would be happy to test/try new notebooks that would help smooth ⤴️ . Thanks again!

**Comment by cassienickles** [comment]
Content has been organized into the PO.DAAC Cookbook now! All tutorials are updated to not have UAT referenced. The cookbook includes cheatsheets with glossaries and tutorials rendered in a more readable way: https://podaac.github.io/tutorials/
