### ISSUE TITLE
AWS S3 access

### ISSUE THREAD

**Issue by sanAkel** [podaac/tutorials#46]
I have been trying to work with different notebooks, and have been having access problems such as the one in this attached notebook
[test1.pdf](https://github.com/podaac/tutorials/files/8667340/test1.pdf)
 

The dataset I am trying to read is [podaac-ops-cumulus-protected/TELLUS_GRAC-GRFO_MASCON_CRI_GRID_RL06_V2/](https://search.earthdata.nasa.gov/downloads/4132314665)

And the notebook I used as an example is a [recent one](https://github.com/podaac/tutorials/blob/master/notebooks/meetings_workshops/workshop_osm_2022/CloudAWS_AmazonRiver_Estuary_Exploration.ipynb).

I verified that my _credentials_ from `get_temp_creds()` look okay. However, 
> s3_file_obj = fs_s3.open(url, mode='rb')

throws an error, please see attachment.

Appreciate any help. Thanks!

**Comment by sanAkel** [comment]
> Hi SanAkel - when you're running the notebook, are you in Amazon Web Services (AWS) region us-west-2? Direct S3 Access only works when you're in the same AWS region as the data.

@mike-gangl Thanks for clarifying that!

My `ip` address would be originating from the east coast (I am at NASA GSFC - via VPN). So I guess to answer your question:

>are you in Amazon Web Services (AWS) region us-west-2?

No!

>Direct S3 Access only works when you're in the same AWS region as the data.

In that case, is there another _access_ port for _direct_ cloud access? 

(Currently I am using `podaac-data-subscriber` tool which works well for data assimilation, however, not so _nice_ for diagnostics and inter-comparisons.)

Suggestions would be much appreciated! Thanks again!

**Comment by mike-gangl** [comment]
so access to data **not** through 'direct s3 access has a few routes, but here i think we can look at 2- HTTPS access and OPeNDAP access.

### opendap
Opendap notebook: https://github.com/podaac/tutorials/blob/master/notebooks/meetings_workshops/workshop_osm_2022/S6_OPeNDAP_Access_Gridding.ipynb

for TELLUS there is only a single granule (i think) so you can access that through OPeNDAP here: https://opendap.earthdata.nasa.gov/collections/C1938032626-POCLOUD/granules/GRCTellus.JPL.200204_202012.GLO.RL06M.MSCNv02CRI.dmr.html

### HTTP access
you can access that file through this endpoint: https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-protected/TELLUS_GRAC-GRFO_MASCON_CRI_GRID_RL06_V2/GRCTellus.JPL.200204_202202.GLO.RL06M.MSCNv02CRI.nc
note you'll need Earthdata Login to access it. This is essentially how the subscriber gets data to download as well.

**Comment by mike-gangl** [comment]
for example of download via https, this notebook has some info: https://github.com/podaac/tutorials/blob/master/notebooks/Pre-SWOT_Numerical_Simulation_Demo.ipynb

that one still tried to do direct s3 access, but 'falls back' to the simple download case.

**Comment by sanAkel** [comment]
Thanks a lot! I will try `opendap` or `http` notebooks - whatever goes easiest!

I had no problems with the `Earthdata Login` it was always with `AWS`.

If I can confirm that these work, I will close this issue. Thanks!

**Comment by mike-gangl** [comment]
@sanAkel - any luck with the tutorials?

**Comment by sanAkel** [comment]
> @sanAkel - any luck with the tutorials?

Sorry @mike-gangl I have not had a chance to come back to this in last few weeks. Thanks for reminding me. (Hopefully the long weekend will give me sometime to wrap loose ends!)

**Comment by sanAkel** [comment]
@mike-gangl I tried both the above examples you listed:
1. [opendap notebook](https://github.com/podaac/tutorials/blob/master/notebooks/meetings_workshops/workshop_osm_2022/S6_OPeNDAP_Access_Gridding.ipynb)
2. [HTTPS download](https://github.com/podaac/tutorials/blob/master/notebooks/Pre-SWOT_Numerical_Simulation_Demo.ipynb)

The second one worked. First one threw error at `files = download_all(urls=reqs, max_workers=12)`.

Thanks for the help. Appreciate it.

Closing this issue.
