### ISSUE TITLE
error downloading data

### ISSUE THREAD

**Issue by fenoglioluciana** [podaac/tutorials#90]
podaac-data-downloader 

does work for me for ocean but not for NA rivers (i.e. does not work for me for 

-c SWOT_SIMULATED_NA_CONTINENT_L2_HR_Raster_V1 -d ./SWOT_SIMULATED_NA_CONTINENT_L2_HR_Raster_V1 --start-date 2022-08-02T00:00:00Z --end-date 2022-08-22T00:00:00Z -b="-97,32.5,-96.5,33"

moreover I use the following command:
python3 podaac-data-downloader.py -c etc. 
therefore I do not know if my issue is related to this, 
the rest does not work

thanks for your reply

**Comment by cassienickles** [comment]
Downloader/subscriber examples are updated with latest version of data release. See PO.DAAC Cookbook examples for SWOT here: https://podaac.github.io/tutorials/quarto_text/SWOT.html#via-command-line---po.daac-subscriberdownloader-examples
